# Generated by Django 2.1.2 on 2018-11-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='avatar',
        ),
    ]
